"""initial schema

Revision ID: 078972d722d3
Revises:
Create Date: 2026-08-15 17:57:18.211551

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "078972d722d3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fpl_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("short_name", sa.String(length=8), nullable=False),
        sa.Column("strength_overall_home", sa.Integer(), nullable=False),
        sa.Column("strength_overall_away", sa.Integer(), nullable=False),
        sa.Column("strength_attack_home", sa.Integer(), nullable=False),
        sa.Column("strength_attack_away", sa.Integer(), nullable=False),
        sa.Column("strength_defence_home", sa.Integer(), nullable=False),
        sa.Column("strength_defence_away", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_fpl_id"), "teams", ["fpl_id"], unique=True)
    op.create_table(
        "fixtures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fpl_id", sa.Integer(), nullable=False),
        sa.Column("event", sa.Integer(), nullable=True),
        sa.Column("kickoff_time", sa.DateTime(), nullable=True),
        sa.Column("finished", sa.Boolean(), nullable=False),
        sa.Column("team_h_id", sa.Integer(), nullable=False),
        sa.Column("team_a_id", sa.Integer(), nullable=False),
        sa.Column("team_h_score", sa.Integer(), nullable=True),
        sa.Column("team_a_score", sa.Integer(), nullable=True),
        sa.Column("team_h_difficulty", sa.Integer(), nullable=True),
        sa.Column("team_a_difficulty", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_a_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_h_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fpl_id", name="uq_fixture_fpl_id"),
    )
    op.create_index(op.f("ix_fixtures_fpl_id"), "fixtures", ["fpl_id"], unique=False)
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fpl_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=False),
        sa.Column("second_name", sa.String(length=64), nullable=False),
        sa.Column("web_name", sa.String(length=64), nullable=False),
        sa.Column("element_type", sa.Integer(), nullable=False),
        sa.Column("now_cost", sa.Integer(), nullable=False),
        sa.Column("selected_by_percent", sa.Float(), nullable=False),
        sa.Column("form", sa.Float(), nullable=False),
        sa.Column("total_points", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("chance_of_playing_next_round", sa.Integer(), nullable=True),
        sa.Column("news", sa.String(length=512), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_players_fpl_id"), "players", ["fpl_id"], unique=True)
    op.create_table(
        "player_gameweek_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("fixture_fpl_id", sa.Integer(), nullable=True),
        sa.Column("opponent_team_fpl_id", sa.Integer(), nullable=True),
        sa.Column("was_home", sa.Boolean(), nullable=True),
        sa.Column("kickoff_time", sa.DateTime(), nullable=True),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("total_points", sa.Integer(), nullable=False),
        sa.Column("goals_scored", sa.Integer(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=False),
        sa.Column("clean_sheets", sa.Integer(), nullable=False),
        sa.Column("goals_conceded", sa.Integer(), nullable=False),
        sa.Column("bonus", sa.Integer(), nullable=False),
        sa.Column("bps", sa.Integer(), nullable=False),
        sa.Column("influence", sa.Float(), nullable=False),
        sa.Column("creativity", sa.Float(), nullable=False),
        sa.Column("threat", sa.Float(), nullable=False),
        sa.Column("ict_index", sa.Float(), nullable=False),
        sa.Column("expected_goals", sa.Float(), nullable=False),
        sa.Column("expected_assists", sa.Float(), nullable=False),
        sa.Column("expected_goal_involvements", sa.Float(), nullable=False),
        sa.Column("expected_goals_conceded", sa.Float(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("selected", sa.Integer(), nullable=False),
        sa.Column("transfers_in", sa.Integer(), nullable=False),
        sa.Column("transfers_out", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "round", name="uq_player_round"),
    )
    op.create_index(
        op.f("ix_player_gameweek_stats_round"), "player_gameweek_stats", ["round"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_gameweek_stats_round"), table_name="player_gameweek_stats")
    op.drop_table("player_gameweek_stats")
    op.drop_index(op.f("ix_players_fpl_id"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_fixtures_fpl_id"), table_name="fixtures")
    op.drop_table("fixtures")
    op.drop_index(op.f("ix_teams_fpl_id"), table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
