"""store FPL expected points on historical rows

Revision ID: 2be79e8ed086
Revises: f823db80b192
Create Date: 2026-08-25 11:05:26.569087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2be79e8ed086"
down_revision: Union[str, Sequence[str], None] = "f823db80b192"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "historical_player_gameweeks", sa.Column("expected_points", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("historical_player_gameweeks", "expected_points")
    # ### end Alembic commands ###
