"""add player gameweek starts

Revision ID: 85f45740b9f4
Revises: 2be721c10000
Create Date: 2026-08-24 18:08:03.232552

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "85f45740b9f4"
down_revision: Union[str, Sequence[str], None] = "2be721c10000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player_gameweek_stats", sa.Column("starts", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player_gameweek_stats", "starts")
    # ### end Alembic commands ###
