"""add point-in-time player and team snapshots

Revision ID: f3714f15cfcc
Revises: 85f45740b9f4
Create Date: 2026-08-25 09:40:02.858011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f3714f15cfcc"
down_revision: Union[str, Sequence[str], None] = "85f45740b9f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("captured_on", sa.Date(), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.Column("next_event", sa.Integer(), nullable=True),
        sa.Column("strength_overall_home", sa.Integer(), nullable=False),
        sa.Column("strength_overall_away", sa.Integer(), nullable=False),
        sa.Column("strength_attack_home", sa.Integer(), nullable=False),
        sa.Column("strength_attack_away", sa.Integer(), nullable=False),
        sa.Column("strength_defence_home", sa.Integer(), nullable=False),
        sa.Column("strength_defence_away", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "captured_on", name="uq_team_snapshot_day"),
    )
    op.create_index(
        op.f("ix_team_snapshots_captured_on"), "team_snapshots", ["captured_on"], unique=False
    )
    op.create_index(op.f("ix_team_snapshots_team_id"), "team_snapshots", ["team_id"], unique=False)
    op.create_table(
        "player_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("captured_on", sa.Date(), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.Column("next_event", sa.Integer(), nullable=True),
        sa.Column("now_cost", sa.Integer(), nullable=False),
        sa.Column("ep_next", sa.Float(), nullable=False),
        sa.Column("form", sa.Float(), nullable=False),
        sa.Column("selected_by_percent", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("chance_of_playing_next_round", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "captured_on", name="uq_player_snapshot_day"),
    )
    op.create_index(
        op.f("ix_player_snapshots_captured_on"), "player_snapshots", ["captured_on"], unique=False
    )
    op.create_index(
        op.f("ix_player_snapshots_player_id"), "player_snapshots", ["player_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_snapshots_player_id"), table_name="player_snapshots")
    op.drop_index(op.f("ix_player_snapshots_captured_on"), table_name="player_snapshots")
    op.drop_table("player_snapshots")
    op.drop_index(op.f("ix_team_snapshots_team_id"), table_name="team_snapshots")
    op.drop_index(op.f("ix_team_snapshots_captured_on"), table_name="team_snapshots")
    op.drop_table("team_snapshots")
    # ### end Alembic commands ###
