"""add historical player gameweeks for model training

Revision ID: f823db80b192
Revises: f3714f15cfcc
Create Date: 2026-08-25 10:06:19.128071

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f823db80b192"
down_revision: Union[str, Sequence[str], None] = "f3714f15cfcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historical_player_gameweeks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season", sa.String(length=16), nullable=False),
        sa.Column("element", sa.Integer(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("fixture", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("position", sa.String(length=8), nullable=True),
        sa.Column("team", sa.String(length=64), nullable=True),
        sa.Column("opponent_team", sa.Integer(), nullable=True),
        sa.Column("was_home", sa.Boolean(), nullable=True),
        sa.Column("kickoff_time", sa.DateTime(), nullable=True),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("starts", sa.Integer(), nullable=True),
        sa.Column("total_points", sa.Integer(), nullable=False),
        sa.Column("bps", sa.Integer(), nullable=False),
        sa.Column("bonus", sa.Integer(), nullable=False),
        sa.Column("goals_scored", sa.Integer(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=False),
        sa.Column("clean_sheets", sa.Integer(), nullable=False),
        sa.Column("goals_conceded", sa.Integer(), nullable=False),
        sa.Column("own_goals", sa.Integer(), nullable=False),
        sa.Column("saves", sa.Integer(), nullable=False),
        sa.Column("yellow_cards", sa.Integer(), nullable=False),
        sa.Column("red_cards", sa.Integer(), nullable=False),
        sa.Column("penalties_missed", sa.Integer(), nullable=False),
        sa.Column("penalties_saved", sa.Integer(), nullable=False),
        sa.Column("influence", sa.Float(), nullable=False),
        sa.Column("creativity", sa.Float(), nullable=False),
        sa.Column("threat", sa.Float(), nullable=False),
        sa.Column("ict_index", sa.Float(), nullable=False),
        sa.Column("expected_goals", sa.Float(), nullable=True),
        sa.Column("expected_assists", sa.Float(), nullable=True),
        sa.Column("expected_goals_conceded", sa.Float(), nullable=True),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("selected", sa.Integer(), nullable=False),
        sa.Column("transfers_in", sa.Integer(), nullable=False),
        sa.Column("transfers_out", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "season", "element", "round", "fixture", name="uq_historical_player_fixture"
        ),
    )
    op.create_index(
        op.f("ix_historical_player_gameweeks_element"),
        "historical_player_gameweeks",
        ["element"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_player_gameweeks_round"),
        "historical_player_gameweeks",
        ["round"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_player_gameweeks_season"),
        "historical_player_gameweeks",
        ["season"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_historical_player_gameweeks_season"), table_name="historical_player_gameweeks"
    )
    op.drop_index(
        op.f("ix_historical_player_gameweeks_round"), table_name="historical_player_gameweeks"
    )
    op.drop_index(
        op.f("ix_historical_player_gameweeks_element"), table_name="historical_player_gameweeks"
    )
    op.drop_table("historical_player_gameweeks")
    # ### end Alembic commands ###
