"""add player birth_date, transfermarkt fields, and injury_records table

Revision ID: f8f876872f5b
Revises: fc0805da33a7
Create Date: 2026-08-15 18:20:55.981213

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f8f876872f5b"
down_revision: Union[str, Sequence[str], None] = "fc0805da33a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "injury_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("season", sa.String(length=8), nullable=False),
        sa.Column("injury_type", sa.String(length=128), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("days_out", sa.Integer(), nullable=True),
        sa.Column("games_missed", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_injury_records_player_id"), "injury_records", ["player_id"], unique=False
    )
    op.add_column("players", sa.Column("birth_date", sa.Date(), nullable=True))
    op.add_column("players", sa.Column("transfermarkt_id", sa.Integer(), nullable=True))
    op.add_column("players", sa.Column("transfermarkt_slug", sa.String(length=128), nullable=True))
    op.add_column(
        "players", sa.Column("transfermarkt_lookup_status", sa.String(length=16), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "transfermarkt_lookup_status")
    op.drop_column("players", "transfermarkt_slug")
    op.drop_column("players", "transfermarkt_id")
    op.drop_column("players", "birth_date")
    op.drop_index(op.f("ix_injury_records_player_id"), table_name="injury_records")
    op.drop_table("injury_records")
    # ### end Alembic commands ###
