"""add player ep_next

Revision ID: fc0805da33a7
Revises: 078972d722d3
Create Date: 2026-08-15 18:08:55.740064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fc0805da33a7"
down_revision: Union[str, Sequence[str], None] = "078972d722d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("ep_next", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "ep_next")
    # ### end Alembic commands ###
